const test = require('node:test'); const assert = require('node:assert/strict');
const { processPayment } = require('./index')._internals;
const event = (x = {}) => ({ identity: { claims: { sub: 'user' } }, arguments: { profileId: 'profile', idempotencyKey: 'key', paymentMethodType: 'card', opaqueDataDescriptor: 'desc', opaqueDataValue: 'sensitive-token', expectedAmount: 100, ...x } });
function store(opts = {}) { let p; let captures = 0; return { deps: { getProfile: async () => ({ id: 'profile', cognitoID: opts.owner || 'user', balance: 100 }), getPayment: async () => p, reserve: async (_, value) => { if (opts.reserveFail || p) throw Error('lost'); p = value; }, capture: async () => { captures++; return { transactionId: 'tx', paymentMethod: opts.rail || 'CARD' }; }, attachTransaction: async (value, tx) => p = { ...value, authNetTransactionId: tx }, finalize: async (value, _old, status, applied) => { if (opts.finalizeFail && !opts.failed) { opts.failed = true; throw Error('persist'); } return p = { ...value, status, balanceApplied: applied }; } }, stats: () => ({ p, captures }) }; }
test('authentication and profile ownership enforced', async () => { await assert.rejects(processPayment({ arguments: event().arguments }, store().deps), /Unauthenticated/); await assert.rejects(processPayment(event(), store({ owner: 'other' }).deps), /access denied/); });
test('stale expected amount rejected and server amount authoritative', async () => { await assert.rejects(processPayment(event({ expectedAmount: 99 }), store().deps), /Balance changed/); const s = store(); const out = await processPayment(event({ amount: 999 }), s.deps); assert.equal(out.amount, 100); });
test('same idempotency key charges once', async () => { const s = store(); await processPayment(event(), s.deps); await processPayment(event(), s.deps); assert.equal(s.stats().captures, 1); });
test('reservation loser never captures', async () => { const s = store({ reserveFail: true }); await assert.rejects(processPayment(event(), s.deps), /Another payment/); assert.equal(s.stats().captures, 0); });
test('processor rail mismatch fails closed', async () => { await assert.rejects(processPayment(event(), store({ rail: 'BANK_ACCOUNT' }).deps), /rail/); });
test('captured id survives and retry finalizes without recharge', async () => { const opts = { finalizeFail: true }; const s = store(opts); await assert.rejects(processPayment(event(), s.deps), /persist/); assert.equal(s.stats().p.authNetTransactionId, 'tx'); await processPayment(event(), s.deps); assert.equal(s.stats().captures, 1); });
test('sensitive token is absent from logs', async () => { const logs = []; const old = console.error; console.error = x => logs.push(String(x)); try { await assert.rejects(processPayment({ arguments: event().arguments }, store().deps)); } finally { console.error = old; } assert.equal(logs.join('').includes('sensitive-token'), false); });
